#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  9 00:47:17 2022

@author: pukar
"""

import web_scraper as gs
import pandas as pd

path = "/usr/local/bin/chromedriver"

df= gs.get_jobs('data scientist', 20, False, path, 15)




